### ISSUE TITLE
Version 0.5.4 causing issues with other plugins

### ISSUE THREAD

**Issue by Dannymx** [vitest-dev/eslint-plugin-vitest#494]
I run `eslint-plugin-simple-import-sort` with auto fix to fix eslint problems, but since I installed `"eslint-plugin-vitest": "^0.5.4"` my auto fixes stopped working and ESLint server is showing some errors, here's the log below:

```
[Info  - 10:15:13 AM] ESLint server is starting.
[Info  - 10:15:13 AM] ESLint server running in node v20.14.0
[Info  - 10:15:13 AM] ESLint server is running.
[Info  - 10:15:15 AM] ESLint library loaded from: /Users/dsaldana/code/<redacted>/node_modules/eslint/lib/api.js
[Error - 10:15:21 AM] Calculating config file for file:///Users/dsaldana/code/<redacted>/src/components/pages/formula/formula-search.tsx) failed.
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'vitest' -> object with constructor 'Object'
    |     property 'configs' -> object with constructor 'Object'
    |     property 'recommended' -> object with constructor 'Object'
    --- property 'plugins' closes the circle
Referenced from: /Users/dsaldana/code/<redacted>/.eslintrc.json
    at JSON.stringify (<anonymous>)
    at /Users/dsaldana/code/<redacted>/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2156:45
    at Array.map (<anonymous>)
    at ConfigValidator.formatErrors (/Users/dsaldana/code/<redacted>/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2147:23)
    at ConfigValidator.validateConfigSchema (/Users/dsaldana/code/<redacted>/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2177:84)
    at ConfigArrayFactory._normalizeConfigData (/Users/dsaldana/code/<redacted>/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3019:19)
    at ConfigArrayFactory._loadExtendedPluginConfig (/Users/dsaldana/code/<redacted>/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3239:25)
    at ConfigArrayFactory._loadExtends (/Users/dsaldana/code/<redacted>/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3154:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/dsaldana/code/<redacted>/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
```

The problem doesn't exist with `"eslint-plugin-vitest": "^0.4.1"`.

I raised an issue [on the other plugin repo](https://github.com/lydell/eslint-plugin-simple-import-sort/issues/178) in case this plugin is not the problem.

**Comment by veritem** [comment]
how does you `.eslintrc.json` look like?

**Comment by Dannymx** [comment]
> how does you `.eslintrc.json` look like?

```
{
  // Configuration for JavaScript files
  "extends": [
    "airbnb-base",
    "next/core-web-vitals", // Needed to avoid warning in next.js build: 'The Next.js plugin was not detected in your ESLint configuration'
    "prettier"
  ],
  "overrides": [
    // Configuration for TypeScript files
    {
      "files": ["**/*.ts", "**/*.tsx", "**/*.mts"],
      "plugins": ["@typescript-eslint", "unused-imports", "simple-import-sort"],
      "extends": [
        "airbnb",
        "airbnb-typescript",
        "next/core-web-vitals",
        "prettier"
      ],
      "parser": "@typescript-eslint/parser",
      "parserOptions": {
        "project": "./tsconfig.json"
      },
      "rules": {
        "import/extensions": "off", // Avoid missing file extension errors, TypeScript already provides a similar feature
        "react/function-component-definition": "off", // Disable Airbnb's specific function type
        "react/destructuring-assignment": "off", // Vscode doesn't support automatically destructuring, it's a pain to add a new variable
        "react/require-default-props": "off", // Allow non-defined react props as undefined
        "react/jsx-props-no-spreading": "off", // _app.tsx uses spread operator and also, react-hook-form
        "@typescript-eslint/comma-dangle": "off", // Avoid conflict rule between Eslint and Prettier
        "@typescript-eslint/consistent-type-imports": "error", // Ensure `import type` is used when it's necessary
        "no-restricted-syntax": [
          "error",
          "ForInStatement",
          "LabeledStatement",
          "WithStatement"
        ], // Overrides Airbnb configuration and enable no-restricted-syntax
        "import/prefer-default-export": "off", // Named export is easier to refactor automatically
        "simple-import-sort/imports": "error", // Import configuration for `eslint-plugin-simple-import-sort`
        "simple-import-sort/exports": "error", // Export configuration for `eslint-plugin-simple-import-sort`
        "import/order": "off", // Avoid conflict rule between `eslint-plugin-import` and `eslint-plugin-simple-import-sort`
        "@typescript-eslint/no-unused-vars": "off",
        "unused-imports/no-unused-imports": "error",
        "unused-imports/no-unused-vars": [
          "error",
          { "argsIgnorePattern": "^_" }
        ]
      }
    },
    {
      "files": ["*.js", "*.jsx", "*.ts", "*.tsx"],
      "rules": {
        "simple-import-sort/imports": [
          "error",
          {
            "groups": [
              [
                // Packages. `react` related packages come first.
                "^react",
                "^@?\\w",
                // Internal packages.
                "^(components|hooks|shared|utils|contexts|helpers|store)(/.*|$)",
                // Side effect imports.
                "^\\u0000",
                // Parent imports. Put `..` last.
                "^\\.\\.(?!/?$)",
                "^\\.\\./?$",
                // Other relative imports. Put same-folder imports and `.` last.
                "^\\./(?=.*/)(?!/?$)",
                "^\\.(?!/?$)",
                "^\\./?$",
                // Style imports.
                "^.+\\.s?css$"
              ]
            ]
          }
        ]
      }
    },
    // Configuration for testing
    {
      "files": ["**/*.test.ts", "**/*.test.tsx"],
      "plugins": ["vitest", "jest-formatting", "testing-library", "jest-dom"],
      "extends": [
        "plugin:vitest/recommended",
        "plugin:jest-formatting/recommended",
        "plugin:testing-library/react",
        "plugin:jest-dom/recommended"
      ]
    }
  ]
}
```

**Comment by veritem** [comment]
change plugin config for vitest from `vitest/recommended` to `vitest/legacy-recommended`. We've moved to the new eslint flat config since v0.5.4

**Comment by veritem** [comment]
@Dannymx I'm going to close this for now. Please re-open this again if you're still facing the same issue.
